-- To run this script: source C:\Users\<user>\Documents\GitHub\Sixerr\database.sql

-- For skill database
-- Query: SELECT * FROM sixerrapp_skill;
-- Delete: DELETE FROM sixerrapp_skill WHERE;
-- Insert: INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('pickleball', 'images/skills/pickleball.jpeg', 1);

-- For user database
-- Query: SELECT username, first_name, last_name, role, skill_id, popularity, rating, hourly_rate, image, email, dummy FROM sixerrapp_user;
-- Delete: DELETE FROM sixerrapp_user WHERE;
-- Insert: INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, bio, ) VALUES ('Chris', 'Paul', 'cp3', 'cp3@gmail.com', 'ThisIsMyPassword', 'mentor', 'pickleball', 0, 0, 1, '2025-03-10', 'images/users/chris.jpg', 1, 1, 4.5, 20.50);

-- Just some random data for skill
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('basketball', 'images/skills/basketball.jpeg', 1);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('animefighting', 'images/skills/anime_fighting.jpg', 2);

INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('pickleball', 'images/skills/pickleball.jpeg', 3);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('coding', 'images/skills/coding.jpg', 4);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('dancing', 'images/skills/dancing.jpg', 5);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('football', 'images/skills/football.jpg', 6);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('drawing', 'images/skills/drawing.jpg', 7);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('painting', 'images/skills/painting.jpg', 8);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('boxing', 'images/skills/boxing.jpg', 9);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('singing', 'images/skills/singing.jpg', 10);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('capoeira', 'images/skills/capoeira.jpg', 11);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('acting', 'images/skills/acting.jpg', 12);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('tennis', 'images/skills/tennis.jpg', 13);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('surfing', 'images/skills/surfing.jpg', 14);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('video editing', 'images/skills/video_editing.jpg', 15);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('writing', 'images/skills/writing.jpg', 16);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('carpentry', 'images/skills/carpentry.jpg', 17);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('breakdancing', 'images/skills/breakdancing.jpg', 18);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('badminton', 'images/skills/badminton.jpg', 19);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('gymnastics', 'images/skills/gymnastics.jpg', 20);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('snowboarding', 'images/skills/snowboarding.jpg', 21);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('american football', 'images/skills/american_football.jpg', 22);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('table tennis', 'images/skills/table_tennis.jpg', 23);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('playing guitar', 'images/skills/playing_guitar.jpg', 24);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('swimming', 'images/skills/swimming.jpg', 25);
INSERT INTO sixerrapp_skill (skill_name, image, popularity) VALUES ('volleyball', 'images/skills/volleyball.jpg', 26);





-- Just some random data for user
-- pickelball
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Chris', 'Paul', 'cp3', 'cp3@gmail.com', 'ThisIsMyPassword', 'mentor', 'pickleball', 0, 0, 1, '2025-03-10', 'images/users/chris.jpg', 1, 67, 4.5, 20.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Donovan', 'Mitchell', 'dm', 'dm@gmail.com', 'ThisIsMyPassword', 'mentor', 'pickleball', 0, 0, 1, '2025-03-10', 'images/users/donovan.jpg', 1, 78, 3.7, 18.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Ja', 'Morant', 'jm', 'jm@gmail.com', 'ThisIsMyPassword', 'mentor', 'pickleball', 0, 0, 1, '2025-03-10', 'images/users/ja.jpg', 1, 85, 4.2, 19.75, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jrue', 'Holiday', 'jh', 'jh@gmail.com', 'ThisIsMyPassword', 'mentor', 'pickleball', 0, 0, 1, '2025-03-10', 'images/users/jrue.jpg', 1, 10, 4.8, 30.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Kevin', 'Durant', 'kd', 'kd@gmail.com', 'ThisIsMyPassword', 'mentor', 'pickleball', 0, 0, 1, '2025-03-10', 'images/users/kevin.jpg', 1, 88, 4.1, 15.99, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Luka', 'Doncic', 'ld', 'ld@gmail.com', 'ThisIsMyPassword', 'mentor', 'pickleball', 0, 0, 1, '2025-03-10', 'images/users/luka.jpg', 1, 105, 3.2, 9.99, 0.0);

-- capoeira
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Victor', 'Wembanyama', 'vw', 'vw@gmail.com', 'ThisIsMyPassword', 'mentor', 'capoeira', 0, 0, 1, '2025-03-10', 'images/users/victor.jpg', 1, 114, 2.1, 5.00, 0.0);

-- dancing
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Paolo', 'Banchero', 'pb', 'pb@gmail.com', 'ThisIsMyPassword', 'mentor', 'dancing', 0, 0, 1, '2025-03-10', 'images/users/paolo.jpg', 1, 38, 4.6, 2.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Michael', 'Jackson', 'mj', 'mj@gmail.com', 'ThisIsMyPassword', 'mentor', 'dancing', 0, 0, 1, '2025-03-17', 'images/users/michael_jackson.jpg', 1, 41, 5.0, 40.00, 0.0);

-- animefighting
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jogo', 'Sukuna', 'js', 'js@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-10', 'images/users/default.jpg', 1, 108, 2.5, 22.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Naruto', 'Uzumaki', 'naru', 'naru@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/naruto.jpg', 1, 22, 4.8, 19.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Saitama', '', 'saitama', 'saitama@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/saitama.jpg', 1, 4, 5.0, 21.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Goku', '', 'goku', 'goku@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/goku.jpg', 1, 12, 4.9, 23.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Vegeta', 'Prince', 'vegeta', 'vegeta@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/vegeta.jpg', 1, 60, 4.7, 27.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Sasuke', 'Uchiha', 'sasuke', 'sasuke@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/sasuke.jpg', 1, 53, 4.6, 18.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Genos', '', 'genos', 'genos@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/genos.jpg', 1, 72, 4.5, 17.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Ichigo', 'Kurosaki', 'ichigo', 'ichigo@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/ichigo.jpg', 1, 35, 4.8, 24.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Roronoa', 'Zoro', 'zoro', 'zoro@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/zoro.jpg', 1, 27, 4.9, 20.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Luffy', 'Monkey D.', 'luffy', 'luffy@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/luffy.jpg', 1, 58, 4.7, 9.99, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Killua', 'Zoldyck', 'killua', 'killua@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/killua.jpg', 1, 81, 4.4, 16.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Gon', 'Freecss', 'gon', 'gon@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/gon.jpg', 1, 83, 4.3, 18.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Levi', 'Ackerman', 'levi', 'levi@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/levi.jpg', 1, 47, 4.9, 19.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Eren', 'Yeager', 'eren', 'eren@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/eren.jpg', 1, 76, 4.6, 21.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Tanjirou', 'Kamado', 'tanjiro', 'tanjiro@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/tanjirou.jpg', 1, 98, 4.5, 24.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Zenitsu', 'Agatsuma', 'zenitsu', 'zenitsu@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/zenistsu.jpg', 1, 94, 4.2, 12.75, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Dio', 'Brando', 'dio', 'dio@gmail.com', 'ThisIsMyPassword', 'mentor', 'animefighting', 0, 0, 1, '2025-03-17', 'images/users/dio.jpg', 1, 66, 4.6, 16.00, 0.0);

-- american_football
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Tom', 'Brady', 'brady12', 'brady@gmail.com', 'ThisIsMyPassword', 'mentor', 'american football', 0, 0, 1, '2025-03-17', 'images/users/tom_brady.jpg', 1, 3, 5.0, 250.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Travis', 'Kelce', 'tkelce87', 'kelce@gmail.com', 'ThisIsMyPassword', 'mentor', 'american football', 0, 0, 1, '2025-03-17', 'images/users/travis_kelce.jpg', 1, 18, 4.8, 22.00, 0.0);

-- badminton
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Dan', 'lin', 'lindan', 'lindan@gmail.com', 'ThisIsMyPassword', 'mentor', 'badminton', 0, 0, 1, '2025-03-17', 'images/users/lin_dan.jpg', 1, 15, 4.9, 23.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Chong Wei', 'Lee', 'leechongwei', 'leechongwei@gmail.com', 'ThisIsMyPassword', 'mentor', 'badminton', 0, 0, 1, '2025-03-17', 'images/users/lee_chong_wei.jpg', 1, 92, 4.8, 21.50, 0.0);

-- basketball
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Michael', 'Jordan', 'mj23', 'mjordan@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/michael_jordan.jpg', 1, 1, 5.0, 1000.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Stephen', 'Curry', 'steph30', 'curry@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/curry.jpg', 1, 5, 5.0, 450.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Giannis', 'Antetokounmpo', 'giannis34', 'giannis@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/giannis.jpg', 1, 17, 4.9, 40.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jayson', 'Tatum', 'tatum0', 'tatum@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/tatum.jpg', 1, 23, 4.8, 35.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Joel', 'Embiid', 'joel21', 'embiid@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/embiid.jpg', 1, 44, 4.7, 25.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Kyrie', 'Irving', 'kyrie11', 'kyrie@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/kyrie.jpg', 1, 32, 4.8, 34.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('James', 'Harden', 'harden13', 'harden@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/harden.jpg', 1, 112, 4.5, 35.60, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Anthony', 'Davis', 'ad3', 'davis@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/ad.jpg', 1, 84, 4.6, 23.20, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Damian', 'Lillard', 'dame0', 'lillard@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/dame.jpg', 1, 40, 4.8, 25.60, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Devin', 'Booker', 'booker1', 'booker@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/booker.jpg', 1, 48, 4.7, 23.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Zion', 'Williamson', 'zion1', 'zion@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/zion.jpg', 1, 109, 4.5, 36.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jimmy', 'Butler', 'jimmy22', 'butler@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/butler.jpg', 1, 19, 4.8, 42.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Kawhi', 'Leonard', 'kawhi2', 'kawhi@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/kawhi.jpg', 1, 21, 4.9, 24.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('DeMar', 'DeRozan', 'demar10', 'derozan@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/demar.jpg', 1, 74, 4.6, 21.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Trae', 'Young', 'trae11', 'trae@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/trae.jpg', 1, 33, 4.7, 18.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('LaMelo', 'Ball', 'lamelo2', 'lamelo@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/lamelo.jpg', 1, 99, 4.5, 16.90, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Magic', 'Johnson', 'magic32', 'magic@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/magic.jpg', 1, 16, 4.8, 23.19, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Larry', 'Bird', 'bird33', 'larry@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/bird.jpg', 1, 7, 4.9, 56.60, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Tim', 'Duncan', 'td21', 'tim@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/duncan.jpg', 1, 45, 4.8, 35.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Dirk', 'Nowitzki', 'dirk41', 'dirk@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/dirk.jpg', 1, 113, 4.7, 19.76, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Allen', 'Iverson', 'ai3', 'iverson@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/ai.jpg', 1, 11, 4.9, 17.38, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Vince', 'Carter', 'vc15', 'vince@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/vince.jpg', 1, 36, 4.8, 6.59, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Nikola', 'Jokic', 'joker15', 'jokic@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/jokic.jpg', 1, 6, 5.0, 31.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jamal', 'Murray', 'jm27', 'jamal@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/murray.jpg', 1, 34, 4.7, 7.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Shai', 'Gilgeous-Alexander', 'sga2', 'shai@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/shai.jpg', 1, 20, 4.8, 54.21, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Karl-Anthony', 'Towns', 'kat32', 'kat@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/kat.jpg', 1, 110, 4.6, 23.40, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Hakeem', 'Olajuwon', 'holajuwon', 'holajuwon@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/hakeem.jpg', 1, 73, 4.8, 19.65, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Patrick', 'Ewing', 'pewing', 'pewing@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/ewing.jpg', 1, 107, 4.2, 18.43, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Charles', 'Barkley', 'cbarkley', 'cbarkley@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/charles.jpg', 1, 86, 4.7, 27.19, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Reggie', 'Miller', 'rmiller', 'rmiller@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/reggie.jpg', 1, 79, 4.2, 13.54, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Dennis', 'Rodman', 'drodman', 'drodman@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/rodman.jpg', 1, 71, 4.6, 19.56, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Steve', 'Nash', 'snash', 'snash@gmail.com', 'ThisIsMyPassword', 'mentor', 'basketball', 0, 0, 1, '2025-03-17', 'images/users/nash.jpg', 1, 52, 4.5, 18.50, 0.0);

-- boxing
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Mike', 'Tyson', 'ironMike', 'tyson@gmail.com', 'ThisIsMyPassword', 'mentor', 'boxing', 0, 0, 1, '2025-03-17', 'images/users/mike_tyson.jpg', 1, 31, 4.7, 15.45, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Muhammad', 'Ali', 'ali', 'ali@gmail.com', 'ThisIsMyPassword', 'mentor', 'boxing', 0, 0, 1, '2025-03-17', 'images/users/ali.jpg', 1, 9, 4.9, 24.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Manny', 'Pacquiao', 'pacman', 'mannypacquiao@gmail.com', 'ThisIsMyPassword', 'mentor', 'boxing', 0, 0, 1, '2025-03-17', 'images/users/manny.jpg', 1, 63, 4.6, 30.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Floyd', 'Mayweather', 'fm', 'floydmayweather@gmail.com', 'ThisIsMyPassword', 'mentor', 'boxing', 0, 0, 1, '2025-03-17', 'images/users/mayweather.jpg', 1, 103, 4.2, 20.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Tyson', 'Fury', 'tfury', 'tysonfury@gmail.com', 'ThisIsMyPassword', 'mentor', 'boxing', 0, 0, 1, '2025-03-17', 'images/users/tyson_fury.jpg', 1, 68, 4.2, 9.99, 0.0);

-- breakdancing
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Paul', 'George', 'pg13', 'paulgeorge@gmail.com', 'ThisIsMyPassword', 'mentor', 'breakdancing', 0, 0, 1, '2025-03-17', 'images/users/pg.jpg', 1, 80, 4.7, 41.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Kyojuro', 'Rengoku', 'rengoku', 'rengoku@gmail.com', 'ThisIsMyPassword', 'mentor', 'breakdancing', 0, 0, 1, '2025-03-17', 'images/users/rengoku.jpg', 1, 106, 3.0, 28.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Tengen', 'Uzui', 'tengen', 'tengen@gmail.com', 'ThisIsMyPassword', 'mentor', 'breakdancing', 0, 0, 1, '2025-03-17', 'images/users/tengen.jpg', 1, 89, 3.2, 18.50, 0.0);


-- football
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Lionel', 'Messi', 'lm10', 'messi@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/messi.jpg', 1, 2, 5.0, 6.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Luis', 'Suárez', 'elPistolero', 'suarez@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/suarez.jpg', 1, 26, 4.7, 3.80, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Cristiano', 'Ronaldo', 'cr7', 'ronaldo@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/ronaldo.jpg', 1, 13, 5.0, 2.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Erling', 'Haaland', 'haaland', 'haaland@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/haaland.jpg', 1, 56, 4.8, 18.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Neymar', 'Jr.', 'neymarjr', 'neymar@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/neymar.jpg', 1, 30, 4.9, 45.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Zinedine', 'Zidane', 'zzidane', 'zzidane@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/zindane.jpg', 1, 102, 3.7, 35.67, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Ronaldinho', 'Gaucho', 'rgaucho', 'rgaucho@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/ronaldinho.jpg', 1, 49, 4.5, 11.46, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Kylian', 'Mbappé', 'kmbappe', 'kmbappe@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/mbappe.jpg', 1, 104, 3.6, 21.67, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Karim', 'Benzema', 'kbenzema', 'kbenzema@gmail.com', 'ThisIsMyPassword', 'mentor', 'football', 0, 0, 1, '2025-03-17', 'images/users/benzema.jpg', 1, 97, 4.2, 41.04, 0.0);


-- painting
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Bob', 'Ross', 'happyTrees', 'bobross@gmail.com', 'ThisIsMyPassword', 'mentor', 'painting', 0, 0, 1, '2025-03-17', 'images/users/bob_ross.jpg', 1, 8, 5.0, 75.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Vincent', 'van Gogh', 'vangogh', 'vangogh@gmail.com', 'ThisIsMyPassword', 'mentor', 'painting', 0, 0, 1, '2025-03-17', 'images/users/van_gogh.jpg', 1, 14, 5.0, 15.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Leonardo', 'da Vinci', 'davinci', 'davinci@gmail.com', 'ThisIsMyPassword', 'mentor', 'painting', 0, 0, 1, '2025-03-17', 'images/users/da_vinci.jpg', 1, 24, 5.0, 20.50, 0.0);
 
-- snowboarding
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Chloe', 'Kim', 'chloekim', 'chloe@gmail.com', 'ThisIsMyPassword', 'mentor', 'snowboarding', 0, 0, 1, '2025-03-17', 'images/users/chloe_kim.jpg', 1, 37, 5.0, 15.75, 0.0);

-- surfing 
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Maui', '', 'maui', 'maui@gmail.com', 'ThisIsMyPassword', 'mentor', 'surfing', 0, 0, 1, '2025-03-17', 'images/users/mauwi.jpg', 1, 64, 4.8, 19.99, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Moana', '', 'moana', 'moana@gmail.com', 'ThisIsMyPassword', 'mentor', 'surfing', 0, 0, 1, '2025-03-17', 'images/users/moana.jpg', 1, 50, 5.0, 9.99, 0.0);

-- swimming
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Michael', 'Phelps', 'phelps', 'phelps@gmail.com', 'ThisIsMyPassword', 'mentor', 'swimming', 0, 0, 1, '2025-03-17', 'images/users/phelps.jpg', 1, 25, 5.0, 35.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Nezuko', 'Kamado', 'nezuko', 'nezuko@gmail.com', 'ThisIsMyPassword', 'mentor', 'swimming', 0, 0, 1, '2025-03-17', 'images/users/nezuko.jpg', 1, 100, 2.5, 23.04, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Inosuke', 'Hashibira', 'inosuke', 'inosuke@gmail.com', 'ThisIsMyPassword', 'mentor', 'swimming', 0, 0, 1, '2025-03-17', 'images/users/inosuke.jpg', 1, 96, 2.3, 10.34, 0.0);

-- table_tennis
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Ma', 'Long', 'malong', 'malong@gmail.com', 'ThisIsMyPassword', 'mentor', 'table tennis', 0, 0, 1, '2025-03-17', 'images/users/ma_long.jpg', 1, 70, 4.6, 40.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Edward', 'Elric', 'edward', 'edward@gmail.com', 'ThisIsMyPassword', 'mentor', 'table tennis', 0, 0, 1, '2025-03-17', 'images/users/edward.jpg', 1, 62, 4.7, 38.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Asta', '', 'asta', 'asta@gmail.com', 'ThisIsMyPassword', 'mentor', 'table tennis', 0, 0, 1, '2025-03-17', 'images/users/asta.jpg', 1, 95, 4.4, 34.00, 0.0);

-- tennis
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Serena', 'Williams', 'serena', 'serena@gmail.com', 'ThisIsMyPassword', 'mentor', 'tennis', 0, 0, 1, '2025-03-17', 'images/users/serena_williams.jpg', 1, 77, 4.6, 25.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Roger', 'Federer', 'fedex', 'federer@gmail.com', 'ThisIsMyPassword', 'mentor', 'tennis', 0, 0, 1, '2025-03-17', 'images/users/federer.jpg', 1, 28, 5.0, 35.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Rafael', 'Nadal', 'rafa', 'nadal@gmail.com', 'ThisIsMyPassword', 'mentor', 'tennis', 0, 0, 1, '2025-03-17', 'images/users/nadal.jpg', 1, 42, 4.9, 22.20, 0.0);

-- volleyball
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Shoyo', 'Hinata', 'shoyo', 'shoyo@gmail.com', 'ThisIsMyPassword', 'mentor', 'volleyball', 0, 0, 1, '2025-03-17', 'images/users/shoyo.jpg', 1, 55, 4.7, 6.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Tobio', 'Kageyama', 'kingkageyama', 'tobio@gmail.com', 'ThisIsMyPassword', 'mentor', 'volleyball', 0, 0, 1, '2025-03-17', 'images/users/tobio.jpg', 1, 29, 4.9, 7.00, 0.0);

-- coding
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Taylor', 'Swift', 'tswift', 'tswift@gmail.com', 'ThisIsMyPassword', 'mentor', 'coding', 0, 0, 1, '2025-03-17', 'images/users/taylor_swift.jpg', 1, 39, 5.0, 25.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Drake', '', 'drake', 'drake@gmail.com', 'ThisIsMyPassword', 'mentor', 'coding', 0, 0, 1, '2025-03-17', 'images/users/drake.jpg', 1, 43, 4.9, 75.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Elon', 'Musk', 'elonmusk', 'elon@gmail.com', 'ThisIsMyPassword', 'mentor', 'coding', 0, 0, 1, '2025-03-17', 'images/users/elon.jpg', 1, 101, 5.0, 1000.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Bill', 'Gates', 'bgates', 'bill@gmail.com', 'ThisIsMyPassword', 'mentor', 'coding', 0, 0, 1, '2025-03-17', 'images/users/gates.jpg', 1, 57, 4.9, 950.00, 0.0);


-- Drawing
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Gordon', 'Ramsay', 'ramsay', 'ramsay@gmail.com', 'ThisIsMyPassword', 'mentor', 'drawing', 0, 0, 1, '2025-03-17', 'images/users/gordon_ramsey', 1, 46, 4.9, 600.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Tyler', 'Blevins', 'ninja', 'ninja@gmail.com', 'ThisIsMyPassword', 'mentor', 'drawing', 0, 0, 1, '2025-03-17', 'images/users/ninja.jpg', 1, 59, 4.7, 550.00, 0.0);

-- Video Edittng
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jason', 'Kidd', 'jkidd', 'jkidd@gmail.com', 'ThisIsMyPassword', 'mentor', 'video editing', 0, 0, 1, '2025-03-17', 'images/users/jkidd.jpg', 1, 91, 3.8, 6.96, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Paul', 'Pierce', 'ppierce', 'ppierce@gmail.com', 'ThisIsMyPassword', 'mentor', 'video editing', 0, 0, 1, '2025-03-17', 'images/users/pierce.jpg', 1, 93, 3.6, 10.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Scottie', 'Pippen', 'sp33', 'scottie@gmail.com', 'ThisIsMyPassword', 'mentor', 'video editing', 0, 0, 1, '2025-03-17', 'images/users/pippen.jpg', 1, 51, 4.7, 30.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Nina', 'Tucker', 'nina', 'nina@gmail.com', 'ThisIsMyPassword', 'mentor', 'video editing', 0, 0, 1, '2025-03-17', 'images/users/nina.jpg', 1, 87, 2.0, 5.00, 0.0);


-- Acting
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Dwayne', 'Johnson', 'therock', 'therock@gmail.com', 'ThisIsMyPassword', 'mentor', 'acting', 0, 0, 1, '2025-03-17', 'images/users/rock.jpg', 1, 82, 4.8, 7.50, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Zendaya', '', 'zendaya', 'zendaya@gmail.com', 'ThisIsMyPassword', 'mentor', 'acting', 0, 0, 1, '2025-03-17', 'images/users/zendeya.jpg', 1, 61, 4.7, 6.80, 0.0);


-- Singing 
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jared', 'McCain', 'jmccain', 'mccain@gmail.com', 'ThisIsMyPassword', 'mentor', 'singing', 0, 0, 1, '2025-03-17', 'images/users/mccain.jpg', 1, 69, 4.6, 25.00, 0.0);




-- playing Guitar
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Simone', 'Biles', 'simone', 'simone@gmail.com', 'ThisIsMyPassword', 'mentor', 'playing guitar', 0, 0, 1, '2025-03-17', 'images/users/simone_biles.jpg', 1, 90, 4.6, 7.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Carlos', 'Yulo', 'carlos', 'carlos@gmail.com', 'ThisIsMyPassword', 'mentor', 'playing guitar', 0, 0, 1, '2025-03-17', 'images/users/carlos_yulo.jpg', 1, 65, 4.8, 9.99, 0.0);

-- carpentry
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Jaylen', 'Brown', 'jb7', 'jbrown@gmail.com', 'ThisIsMyPassword', 'mentor', 'carpentry', 0, 0, 1, '2025-03-17', 'images/users/jb.jpg', 1, 75, 4.6, 28.00, 0.0);
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('Giyu', 'Tomioka', 'giyu', 'giyu@gmail.com', 'ThisIsMyPassword', 'mentor', 'carpentry', 0, 0, 1, '2025-03-17', 'images/users/giyu.jpg', 1, 111, 3.1, 25.00, 0.0);

-- Writing 
INSERT INTO sixerrapp_user (first_name, last_name, username, email, password, role, skill_id, is_superuser, is_staff, is_active, date_joined, image, dummy, popularity, rating, hourly_rate, balance) VALUES ('J.K.', 'Rowling', 'jkrowling', 'jkrowling@gmail.com', 'ThisIsMyPassword', 'mentor', 'writing', 0, 0, 1, '2025-03-17', 'images/users/jk_rowling.jpg', 1, 54, 4.9, 7.00, 0.0);







