# Generated by Django 5.1.6 on 2025-03-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SixerrApp', '0004_skill_alter_user_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('admin', 'Admin'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
