# Generated by Django 5.1.6 on 2025-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SixerrApp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
