# Generated by Django 5.1.6 on 2025-03-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SixerrApp', '0007_alter_user_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
