# Generated by Django 5.1.6 on 2025-03-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SixerrApp', '0009_user_image_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
