# Generated by Django 5.1.6 on 2025-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SixerrApp', '0010_user_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
